### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by laurik-de** [ljmc2000/NoiseLooper#7]
Installed version 1.0.4 from F-Droid and the app doesn't start. It just instantly crashes. I'm on Android 14 One UI 6. I tried reinstalling and it didn't work.

**Comment by ljmc2000** [comment]
So fixing this took like 2 and a half hours. Not for any decent reason, the first 2 hours and 15 minutes were spent trying to setup an android emulator. I'm kinda spoiled with having a physical device and also waydroid, so I've never had to use it before. Once that mess was sorted the problem made itself apparent immediately. See the attached pull request if you want a laugh.

**Comment by GreggBandy** [comment]
Still crashing on startup. Android 14 w/ One UI 6

**Comment by ljmc2000** [comment]
@GreggBandy Yes it is. That's because the patch that fixes the problem hasn't been merged into main. I'll be making a release later tonight closing off all currently open pull requests. It won't reach fdroid for several days, but you'll be able to download an APK from the release notes if you can't wait.
